#!/bin/bash

cd lede

git clone https://github.com/rufengsuixing/luci-app-adguardhome package/myapp/luci-app-adguardhome
git clone https://github.com/2512500960/zzu-minieap-openwrt package/myapp/zzu-minieap-openwrt
git clone https://github.com/tty228/luci-app-serverchan package/myapp/luci-app-serverchan
git clone https://github.com/project-lede/luci-app-godproxy package/myapp/luci-app-godproxy
#git clone https://github.com/tuanqing/install-program package/myapp/install-program
# helloworld&&lienol
sed -i '$a src-git helloworld https://github.com/fw876/helloworld' feeds.conf.default
sed -i '$a src-git lienol https://github.com/Lienol/openwrt-package' feeds.conf.default

./scripts/feeds update -a
./scripts/feeds install -a
#sed -i '34 s/$/ +libselinux +libsepol/' feeds/packages/utils/lvm2/Makefile
#sed -i '34 s/$/ +libselinux/' feeds/packages/utils/vim/Makefile
sed -i '/FEATURES+=/ { s/cpiogz //; s/ext4 //; s/ramdisk //; s/squashfs //; }' target/linux/armvirt/Makefile

sed -i '$d' target/linux/armvirt/image/Makefile
echo -e 'define Device/Phicomm-n1
DEVICE_MODEL := Phicomm-n1
  DEVICE_PACKAGES := \
    brcmfmac-firmware-43430-sdio \
    brcmfmac-firmware-43430-sdio-rpi-3b \
    brcmfmac-firmware-43455-sdio \
    brcmfmac-firmware-43455-sdio-rpi-3b-plus \
    kmod-brcmfmac kmod-brcmutil kmod-cfg80211 kmod-mac80211 wpa-cli wpad-basic\
    kmod-fs-ext4 kmod-fs-vfat kmod-fs-exfat libzstd \
    kmod-usb-storage kmod-usb-storage-extras kmod-usb-storage-uas \
    kmod-usb-net kmod-usb-net-asix-ax88179 kmod-usb-net-rtl8150 kmod-usb-net-rtl8152 \
    libattr  cfdisk  resize2fs tune2fs pv unzip \
    lscpu htop iperf3 curl lm-sensors \
	perl perlbase-base perlbase-unicode perlbase-utf8 \
    blkid fdisk lsblk parted \
	attr btrfs-progs chattr dosfstools e2fsprogs f2fs-tools f2fsck lsattr mkf2fs xfs-fsck xfs-mkfs \
    bash gawk getopt losetup tar uuidgen bash bzip2 vim
endef
ifeq ($(SUBTARGET),64)
  TARGET_DEVICES += Phicomm-n1
endif\n
$(eval $(call BuildImage))' >> ./target/linux/armvirt/image/Makefile

cp ../.github/n1.config .config 
make defconfig

